[package]
edition = "2021"
name = "bday"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.150"
rustc-hash = "1.1.0"

[profile.release]
debug = true
